In [21]:
import pandas as pd
import numpy as np

n_clientes=10
data = {
    'ID_Cliente': range(1001, 1001 + n_clientes),
    'Edad': np.random.randint(18, 80, size=n_clientes),
    'Salario_Estimado': np.random.choice([np.nan, 2500, 4000, 5500, 8000], size=n_clientes), # Con nulos
    'Saldo_Bancario': np.random.uniform(0, 50000, size=n_clientes),
    'Estado_Civil': np.random.choice(['Soltero', 'Casado', 'Divorciado', np.nan], size=n_clientes), # Con nulos
    'Genero': np.random.choice(['Masculino', 'Femenino'], size=n_clientes),
    'Nivel_Educativo': np.random.choice(['Secundario', 'Universitario', 'Posgrado'], size=n_clientes),
    'Acepta_Tarjeta': np.random.choice([0, 1], size=n_clientes) # Target
}

# Crear DataFrame
df_clientes = pd.DataFrame(data)
df_clientes

,ID_Cliente,Edad,Salario_Estimado,Saldo_Bancario,Estado_Civil,Genero,Nivel_Educativo,Acepta_Tarjeta
0,1001,56,4000.0,46893.309791,nan,Masculino,Posgrado,0
1,1002,39,4000.0,36676.866396,Soltero,Femenino,Posgrado,0
2,1003,21,NaN,24497.404578,Casado,Femenino,Universitario,1
3,1004,24,2500.0,14801.056871,nan,Masculino,Secundario,0
4,1005,67,4000.0,32885.406371,Soltero,Femenino,Posgrado,1
5,1006,71,4000.0,7584.082954,Casado,Femenino,Secundario,1
6,1007,69,NaN,13482.411923,nan,Femenino,Universitario,0
7,1008,29,8000.0,39215.154479,Casado,Femenino,Posgrado,0
8,1009,52,NaN,42505.901424,Divorciado,Masculino,Posgrado,1
9,1010,25,4000.0,16805.937562,Casado,Masculino,Posgrado,0

In [27]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID_Cliente        10 non-null     int64
 1   Edad              10 non-null     int64
 2   Salario_Estimado  7 non-null      float64
 3   Saldo_Bancario    10 non-null     float64
 4   Estado_Civil      7 non-null      object
 5   Genero            10 non-null     object
 6   Nivel_Educativo   10 non-null     object
 7   Acepta_Tarjeta    10 non-null     int64
dtypes: float64(2), int64(3), object(3)
memory usage: 772.0+ bytes

In [7]:
num=df_clientes.select_dtypes(include=np.number).columns
num

Index(['ID_Cliente', 'Edad', 'Salario_Estimado', 'Saldo_Bancario',
       'Acepta_Tarjeta'],
      dtype='object')

In [8]:
num=df_clientes.select_dtypes(include=np.object_).columns
num

Index(['Estado_Civil', 'Genero', 'Nivel_Educativo'], dtype='object')

In [39]:
#imputar valores faltantes


df_clientes['Estado_Civil']=df_clientes['Estado_Civil'].fillna(df_clientes['Estado_Civil'].mode()[0])
df_clientes

,ID_Cliente,Edad,Salario_Estimado,Saldo_Bancario,Estado_Civil,Genero,Nivel_Educativo,Acepta_Tarjeta
0,1001,56,4000.0,46893.309791,Casado,Masculino,Posgrado,0
1,1002,39,4000.0,36676.866396,Soltero,Femenino,Posgrado,0
2,1003,21,NaN,24497.404578,Casado,Femenino,Universitario,1
3,1004,24,2500.0,14801.056871,Casado,Masculino,Secundario,0
4,1005,67,4000.0,32885.406371,Soltero,Femenino,Posgrado,1
5,1006,71,4000.0,7584.082954,Casado,Femenino,Secundario,1
6,1007,69,NaN,13482.411923,Casado,Femenino,Universitario,0
7,1008,29,8000.0,39215.154479,Casado,Femenino,Posgrado,0
8,1009,52,NaN,42505.901424,Divorciado,Masculino,Posgrado,1
9,1010,25,4000.0,16805.937562,Casado,Masculino,Posgrado,0

In [26]:
df_clientes['Estado_Civil'] = df_clientes['Estado_Civil'].replace('nan', np.nan)
df_clientes

,ID_Cliente,Edad,Salario_Estimado,Saldo_Bancario,Estado_Civil,Genero,Nivel_Educativo,Acepta_Tarjeta
0,1001,56,4000.0,46893.309791,NaN,Masculino,Posgrado,0
1,1002,39,4000.0,36676.866396,Soltero,Femenino,Posgrado,0
2,1003,21,NaN,24497.404578,Casado,Femenino,Universitario,1
3,1004,24,2500.0,14801.056871,NaN,Masculino,Secundario,0
4,1005,67,4000.0,32885.406371,Soltero,Femenino,Posgrado,1
5,1006,71,4000.0,7584.082954,Casado,Femenino,Secundario,1
6,1007,69,NaN,13482.411923,NaN,Femenino,Universitario,0
7,1008,29,8000.0,39215.154479,Casado,Femenino,Posgrado,0
8,1009,52,NaN,42505.901424,Divorciado,Masculino,Posgrado,1
9,1010,25,4000.0,16805.937562,Casado,Masculino,Posgrado,0

In [28]:
from sklearn.impute import SimpleImputer

imputer=SimpleImputer(strategy='most_frequent')
df_clientes['Estado_Civil']=imputer.fit_transform(df_clientes[['Estado_Civil']]).ravel()
df_clientes

,ID_Cliente,Edad,Salario_Estimado,Saldo_Bancario,Estado_Civil,Genero,Nivel_Educativo,Acepta_Tarjeta
0,1001,56,4000.0,46893.309791,Casado,Masculino,Posgrado,0
1,1002,39,4000.0,36676.866396,Soltero,Femenino,Posgrado,0
2,1003,21,NaN,24497.404578,Casado,Femenino,Universitario,1
3,1004,24,2500.0,14801.056871,Casado,Masculino,Secundario,0
4,1005,67,4000.0,32885.406371,Soltero,Femenino,Posgrado,1
5,1006,71,4000.0,7584.082954,Casado,Femenino,Secundario,1
6,1007,69,NaN,13482.411923,Casado,Femenino,Universitario,0
7,1008,29,8000.0,39215.154479,Casado,Femenino,Posgrado,0
8,1009,52,NaN,42505.901424,Divorciado,Masculino,Posgrado,1
9,1010,25,4000.0,16805.937562,Casado,Masculino,Posgrado,0

In [50]:
df_procesado=pd.get_dummies(df_clientes, columns=['Estado_Civil'],drop_first=True)
df_procesado

,ID_Cliente,Edad,Salario_Estimado,Saldo_Bancario,Genero,Nivel_Educativo,Acepta_Tarjeta,Estado_Civil_Divorciado,Estado_Civil_Soltero
0,1001,56,4000.0,46893.309791,Masculino,Posgrado,0,False,False
1,1002,39,4000.0,36676.866396,Femenino,Posgrado,0,False,True
2,1003,21,NaN,24497.404578,Femenino,Universitario,1,False,False
3,1004,24,2500.0,14801.056871,Masculino,Secundario,0,False,False
4,1005,67,4000.0,32885.406371,Femenino,Posgrado,1,False,True
5,1006,71,4000.0,7584.082954,Femenino,Secundario,1,False,False
6,1007,69,NaN,13482.411923,Femenino,Universitario,0,False,False
7,1008,29,8000.0,39215.154479,Femenino,Posgrado,0,False,False
8,1009,52,NaN,42505.901424,Masculino,Posgrado,1,True,False
9,1010,25,4000.0,16805.937562,Masculino,Posgrado,0,False,False

In [66]:
df_clientes['Nivel_Educativo'].unique()

array(['Posgrado', 'Universitario', 'Secundario'], dtype=object)

In [67]:
df_clientes['Nivel_Educativo'].str.lower().str.strip().unique()

array(['posgrado', 'universitario', 'secundario'], dtype=object)

In [30]:
df_procesado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID_Cliente               10 non-null     int64
 1   Edad                     10 non-null     int64
 2   Salario_Estimado         7 non-null      float64
 3   Saldo_Bancario           10 non-null     float64
 4   Genero                   10 non-null     object
 5   Nivel_Educativo          10 non-null     object
 6   Acepta_Tarjeta           10 non-null     int64
 7   Estado_Civil_Casado      10 non-null     bool
 8   Estado_Civil_Divorciado  10 non-null     bool
 9   Estado_Civil_Soltero     10 non-null     bool
dtypes: bool(3), float64(2), int64(3), object(2)
memory usage: 722.0+ bytes

In [51]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
encoder=OneHotEncoder(sparse_output=False)
df_procesado['Genero']=encoder.fit_transform(df_procesado[['Genero']])
df_procesado

,ID_Cliente,Edad,Salario_Estimado,Saldo_Bancario,Genero,Nivel_Educativo,Acepta_Tarjeta,Estado_Civil_Divorciado,Estado_Civil_Soltero
0,1001,56,4000.0,46893.309791,0.0,Posgrado,0,False,False
1,1002,39,4000.0,36676.866396,1.0,Posgrado,0,False,True
2,1003,21,NaN,24497.404578,1.0,Universitario,1,False,False
3,1004,24,2500.0,14801.056871,0.0,Secundario,0,False,False
4,1005,67,4000.0,32885.406371,1.0,Posgrado,1,False,True
5,1006,71,4000.0,7584.082954,1.0,Secundario,1,False,False
6,1007,69,NaN,13482.411923,1.0,Universitario,0,False,False
7,1008,29,8000.0,39215.154479,1.0,Posgrado,0,False,False
8,1009,52,NaN,42505.901424,0.0,Posgrado,1,True,False
9,1010,25,4000.0,16805.937562,0.0,Posgrado,0,False,False

In [43]:
label=LabelEncoder().fit_transform(df_procesado['Nivel_Educativo'])
label

array([0, 0, 2, 1, 0, 1, 2, 0, 0, 0])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
orden_ordinal=[['secundario','universitario','posgrado']]
encoder_ordinal=OrdinalEncoder(categories=orden_ordinal)
df_procesado['Nivel_Educativo']=encoder_ordinal.fit_transform(df_procesado[['Nivel_Educativo']])
df_procesado

,ID_Cliente,Edad,Salario_Estimado,Saldo_Bancario,Genero,Nivel_Educativo,Acepta_Tarjeta,Estado_Civil_Divorciado,Estado_Civil_Soltero
0,1001,56,4000.0,46893.309791,0.0,2.0,0,False,False
1,1002,39,4000.0,36676.866396,1.0,2.0,0,False,True
2,1003,21,NaN,24497.404578,1.0,1.0,1,False,False
3,1004,24,2500.0,14801.056871,0.0,0.0,0,False,False
4,1005,67,4000.0,32885.406371,1.0,2.0,1,False,True
5,1006,71,4000.0,7584.082954,1.0,0.0,1,False,False
6,1007,69,NaN,13482.411923,1.0,1.0,0,False,False
7,1008,29,8000.0,39215.154479,1.0,2.0,0,False,False
8,1009,52,NaN,42505.901424,0.0,2.0,1,True,False
9,1010,25,4000.0,16805.937562,0.0,2.0,0,False,False

In [53]:
df_procesado.dropna(inplace=True)

In [54]:
df_procesado

,ID_Cliente,Edad,Salario_Estimado,Saldo_Bancario,Genero,Nivel_Educativo,Acepta_Tarjeta,Estado_Civil_Divorciado,Estado_Civil_Soltero
0,1001,56,4000.0,46893.309791,0.0,2.0,0,False,False
1,1002,39,4000.0,36676.866396,1.0,2.0,0,False,True
3,1004,24,2500.0,14801.056871,0.0,0.0,0,False,False
4,1005,67,4000.0,32885.406371,1.0,2.0,1,False,True
5,1006,71,4000.0,7584.082954,1.0,0.0,1,False,False
7,1008,29,8000.0,39215.154479,1.0,2.0,0,False,False
9,1010,25,4000.0,16805.937562,0.0,2.0,0,False,False

In [55]:
df_escalado=df_procesado.copy()
df_escalado

,ID_Cliente,Edad,Salario_Estimado,Saldo_Bancario,Genero,Nivel_Educativo,Acepta_Tarjeta,Estado_Civil_Divorciado,Estado_Civil_Soltero
0,1001,56,4000.0,46893.309791,0.0,2.0,0,False,False
1,1002,39,4000.0,36676.866396,1.0,2.0,0,False,True
3,1004,24,2500.0,14801.056871,0.0,0.0,0,False,False
4,1005,67,4000.0,32885.406371,1.0,2.0,1,False,True
5,1006,71,4000.0,7584.082954,1.0,0.0,1,False,False
7,1008,29,8000.0,39215.154479,1.0,2.0,0,False,False
9,1010,25,4000.0,16805.937562,0.0,2.0,0,False,False

In [57]:
num_escalada=df_escalado.select_dtypes(include=np.number).columns
num_escalada

Index(['ID_Cliente', 'Edad', 'Salario_Estimado', 'Saldo_Bancario', 'Genero',
       'Nivel_Educativo', 'Acepta_Tarjeta'],
      dtype='object')

In [59]:
from sklearn.preprocessing import StandardScaler #distribucion normal con media 0 y desviación standar 1
scaler=StandardScaler()
cols_num=['Edad', 'Salario_Estimado', 'Saldo_Bancario','Nivel_Educativo']
df_escalado[cols_num]=scaler.fit_transform(df_escalado[cols_num])
df_escalado

,ID_Cliente,Edad,Salario_Estimado,Saldo_Bancario,Genero,Nivel_Educativo,Acepta_Tarjeta,Estado_Civil_Divorciado,Estado_Civil_Soltero
0,1001,0.623409,-0.226805,1.399379,0.0,0.632456,0,False,False
1,1002,-0.292463,-0.226805,0.649130,1.0,0.632456,0,False,True
3,1004,-1.100586,-1.179384,-0.957330,0.0,-1.581139,0,False,False
4,1005,1.216032,-0.226805,0.370702,1.0,0.632456,1,False,True
5,1006,1.431532,-0.226805,-1.487311,1.0,-1.581139,1,False,False
7,1008,-0.831212,2.313407,0.835530,1.0,0.632456,0,False,False
9,1010,-1.046711,-0.226805,-0.810100,0.0,0.632456,0,False,False

In [60]:
X=df_escalado.drop(['Acepta_Tarjeta','ID_Cliente'],axis=1)
X

,Edad,Salario_Estimado,Saldo_Bancario,Genero,Nivel_Educativo,Estado_Civil_Divorciado,Estado_Civil_Soltero
0,0.623409,-0.226805,1.399379,0.0,0.632456,False,False
1,-0.292463,-0.226805,0.649130,1.0,0.632456,False,True
3,-1.100586,-1.179384,-0.957330,0.0,-1.581139,False,False
4,1.216032,-0.226805,0.370702,1.0,0.632456,False,True
5,1.431532,-0.226805,-1.487311,1.0,-1.581139,False,False
7,-0.831212,2.313407,0.835530,1.0,0.632456,False,False
9,-1.046711,-0.226805,-0.810100,0.0,0.632456,False,False

In [65]:
int(False)

0

In [62]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Edad                     7 non-null      float64
 1   Salario_Estimado         7 non-null      float64
 2   Saldo_Bancario           7 non-null      float64
 3   Genero                   7 non-null      float64
 4   Nivel_Educativo          7 non-null      float64
 5   Estado_Civil_Divorciado  7 non-null      bool
 6   Estado_Civil_Soltero     7 non-null      bool
dtypes: bool(2), float64(5)
memory usage: 350.0 bytes

In [61]:
y=df_escalado['Acepta_Tarjeta']
y

0    0
1    0
3    0
4    1
5    1
7    0
9    0
Name: Acepta_Tarjeta, dtype: int64

In [ ]:
#validación cruzada método retención
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)